<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Manager</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Contact Manager</a>

        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="/contacts">List</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/contacts/add">Add Contact  <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/contacts/export">Export Contacts to CSV</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/logout">Logout</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="/contacts">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </nav>

    <div class="container mt-4">
        <form method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label for="nameInput">Name</label>
                <input type="text" class="form-control" id="nameInput" placeholder="Name" name="name" value="<?= isset($contact) ? $contact->name : '' ?>">
            </div>
            <div class="form-group">
                <label for="emailInput">Email</label>
                <input type="email" class="form-control" id="emailInput" placeholder="Email" name="email" value="<?= isset($contact) ? $contact->email : '' ?>">
            </div>
            <div class="form-group">
                <label for="phoneInput">Phone</label>
                <input type="text" class="form-control" id="phoneInput" placeholder="Phone" name="phone" value="<?= isset($contact) ? $contact->phone : '' ?>">
            </div>
            <div class="form-group">
                <label for="imageInput">Image</label>
                <input type="file" class="form-control" id="imageInput" placeholder="Image" name="image">
                <?php if (isset($contact) && $contact->image) : ?>
                    <img src="/<?= $contact->image ?>" width="200">
                <?php endif; ?>

            </div>

            <button class="btn btn-primary" type="submit"><?= isset($contact) ? 'Save' : 'Add' ?></button>
        </form>
    </div>
</body>
</html>